// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools 2015 v1.7.160
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NpmTaskRunner
{
    static class Vsix
    {
        public const string Id = "a7f89ba3-815c-4feb-89b9-68d1654e213a";
        public const string Name = "Cordova TypeScript Template";
        public const string Description = "Template to start Cordova development using TypeScript";
        public const string Language = "en-US";
        public const string Version = "1.3";
        public const string Author = "rido";
        public const string Tags = "cordova, typescript, mobile";
    }
}
